baseurl = "https://haapakorva.fi/"
title = "Pasi Haapakorva"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Pasi Haapakorva"
disqusShortname = "XXX"
googleAnalytics = "XXX"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Pasi Haapakorva"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Haapakorva"
    #description = "Data-tiede, "
    github = "https://github.com/pasipasi123/"
    flickr = "https://www.flickr.com/photos/pasipasi/"
    #gitlab = "https://gitlab.com/XXX"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/pasi_pasi"
    #stackoverflow = "https://stackoverflow.com/users/5554617/pasipasi"
    email = "pasi.haapakorva[a]gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
 
[[menu.main]]   
    name = "Pasi"
    url = "/page/pasi/"
    weight = 2
    
[[menu.main]]   
    name = "Kivisydänprojekti"
    url = "/page/kivisydänprojekti/"
    weight = 3

