---
title: Pasi
author: Pasi Haapakorva
date: '2018-09-20'
slug: pasi
categories: []
tags: []
description: ''
---

Olen Pasi Haapakorva, oululainen tutkijakoulutettava sosiaalipolitiikan oppiaineessa. Vuodesta 2015 lähtien olen ollut töissä THL:n syntymäkohorttitutkimusryhmässä. Olen myös aktiivinen liikenne- ja kaupunkipolitiikassa. Olen ollut Oulun polkupyöräilijät ry:n hallituksen jäsen yhdistyksen perustamisesta vuonna 2013 lähtien ja sen puheenjohtajana vuodesta 2015 alkaen. Vuosina 2015–2016 olin jäsen Pyöräliiton hallituksessa. 

Teen työkseni tutkimusta. Tutkimukseni on täysin kvantitatiivista: kirjoitan enemmän ohjelmakoodia kuin tekstiä. Tilasto-ohjelmoin R-kielellä käyttäen R- ja Rstudio-ohjelmistoja, jotka ovat avoimia ja ilmaisia, joten voin harrastaa ohjelmointia myös kotikoneellani. 

Kirjoitan blogissani vapaa-ajan tilasto-ohjelmoinnistani. Lisäksi kirjoitan liikennepolitiikasta ja todennäköisesti myös muusta vapaa-ajan ajattelustani ja tekemisistäni kuten oluesta, kahvista, ilmastonmuutoksesta ja valokuvauksesta. Kaitpa perhe-elämä ilman autoa voidaan myös nykyään lukea harrastukseksi. Saatan kirjoittaa työasioistanikin.

Käytän blogialustana blogdownia, joka on rakennettu Hugon päälle ajatellen R-ohjelmoijia. Kirjoitan tekstit Markdown tai R Markdown -kielellä. Ideana on, että tekstin sekaan on luontevaa kirjoittaa R-ohjelmakoodia.

